name: my_test_api  # Changed from test_api to my_test_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4  # or latest version
  dio: ^5.4.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  # State Management
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
